image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable bionic main" > /etc/apt/sources.list.d/gazebo-stable.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt update
          - apt install -y
            build-essential wget cmake cppcheck git mercurial
            qtbase5-dev libqwt-qt5-dev libtinyxml2-dev libprotoc-dev libprotobuf-dev
            libignition-cmake1-dev
            libignition-common2-dev
            libignition-math6-dev
            libignition-msgs2-dev
            libignition-rendering2-dev
            libignition-tools-dev
            libignition-transport5-dev
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git -b v1.14
          - cd lcov
          - make install
          - cd ..
          # Static checking before building
          - sh tools/code_check.sh
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          # Tests currently fail, graphics issue?
          # - make test
