image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - apt update
          - apt -y install wget lsb-release gnupg
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
          - sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-prerelease `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-prerelease.list'
          - wget http://packages.osrfoundation.org/gazebo.key -O - | apt-key add -
          - apt update
          - apt install -y
            build-essential wget cmake cppcheck git mercurial g++-8
            qtbase5-dev libtinyxml2-dev libprotoc-dev libprotobuf-dev
            qtdeclarative5-dev
            qtquickcontrols2-5-dev
            qml-module-qtquick2
            qml-module-qtquick-controls
            qml-module-qtquick-controls2
            qml-module-qtquick-dialogs
            qml-module-qtquick-layouts
            qml-module-qt-labs-folderlistmodel
            qml-module-qt-labs-settings
          - update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 800 --slave /usr/bin/g++ g++ /usr/bin/g++-8 --slave /usr/bin/gcov gcov /usr/bin/gcov-8
          - gcc -v
          - g++ -v
          - gcov -v
          # lcov
          - git clone https://github.com/linux-test-project/lcov.git
          - cd lcov
          - make install
          - cd ..
          # Dependency: Ignition packages
          - apt-get -y install
            libignition-cmake2-dev
            libignition-common3-dev
            libignition-math6-dev
            libignition-msgs3-dev
            libignition-plugin1-dev
            libignition-rendering-dev
            libignition-tools-dev
            libignition-transport6-dev
          # Ignition rendering (uncomment if a specific branch is needed)
          # - apt install -y
          #   libogre-1.9-dev
          #   libglew-dev libfreeimage-dev freeglut3-dev libxmu-dev libxi-dev
          # - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b render_node_gz11
          # - cd ign-rendering
          # - mkdir build
          # - cd build
          # - cmake ..
          # - make -j4 install
          # - cd ../..
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - make codecheck
          # Tests currently fail, graphics issue?
          # - make test
