image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt update
          - apt install -y
            build-essential wget cmake cppcheck mercurial
            qtbase5-dev libqwt-qt5-dev libtinyxml2-dev libprotobuf-dev
            libignition-cmake-dev
            libignition-math4-dev
            libignition-common-dev
            libignition-msgs-dev
            libignition-transport3-dev
            libogre-1.9-dev
          # Static checking before building
          - sh tools/code_check.sh
          # Ignition rendering
          - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b default
          - cd ign-rendering
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          # Tests currently fail, graphics issue?
          # - make test
