image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt install -y build-essential cmake qtbase5-dev libtinyxml2-dev
          - mkdir build
          - cd build
          - cmake ..
          - make
          - make test
