image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt install cmake
          - mkdir build
          - cd build
          - cmake ..
          - make
          - make test
