image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - apt update
          - apt install -y
            build-essential wget cmake cppcheck mercurial
            qtbase5-dev libqwt-qt5-dev libtinyxml2-dev libprotoc-dev libprotobuf-dev
            libignition-tools-dev
            libogre-1.9-dev
          # Static checking before building
          - sh tools/code_check.sh
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b c++17
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b gcc8_c++17
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition common
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common -b bionic
          - cd ign-common
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition msgs
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b proto3
          - cd ign-msgs
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition transport
          - hg clone http://bitbucket.org/ignitionrobotics/ign-transport -b proto3_bionic
          - cd ign-transport
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..

          # Ignition rendering
          - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b default
          - cd ign-rendering
          - mkdir build
          - cd build
          - cmake .. # -DENABLE_TESTS_COMPILATION=false
          - make -j4 install
          - cd ../..
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          # Tests currently fail, graphics issue?
          # - make test
