image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - apt update
          - apt install -y
            build-essential wget cmake
            qtbase5-dev libtinyxml2-dev libfreeimage-dev
            libgts-dev uuid-dev libswscale-dev libavutil-dev libavcodec-dev libavformat-dev
            libprotoc-dev libprotobuf-dev libzmq3-dev protobuf-compiler cppcheck mercurial
          # Static checking before building
          - sh tools/code_check.sh
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b default
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake .. -DENABLE_TESTS_COMPILATION=false
          - make install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b ign-math4
          - cd ign-math
          - mkdir build
          - cd build
          - cmake .. -DENABLE_TESTS_COMPILATION=false
          - make install
          - cd ../..
          # Ignition common
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common -b default
          - cd ign-common
          - mkdir build
          - cd build
          - cmake .. -DENABLE_TESTS_COMPILATION=false
          - make install
          - cd ../..
          # Ignition msgs
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b ign-msgs1
          - cd ign-msgs
          - mkdir build
          - cd build
          - cmake .. -DENABLE_TESTS_COMPILATION=false
          - make install
          - cd ../..
          # Ignition transport
          - hg clone http://bitbucket.org/ignitionrobotics/ign-transport -b ign-transport4
          - cd ign-transport
          - mkdir build
          - cd build
          - cmake .. -DENABLE_TESTS_COMPILATION=false
          - make install
          - cd ../..
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make install
          # Tests currently fail, graphics issue?
          # - make test
