image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable xenial main" > /etc/apt/sources.list.d/gazebo-stable.list
          - echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-prerelease xenial main" > /etc/apt/sources.list.d/gazebo-prerelease.list
          - apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys D2486D2DD83DB69272AFE98867170598AF249743
          - apt update
          - apt install -y build-essential wget cmake cppcheck mercurial
            libfreeimage-dev libgts-dev uuid-dev libswscale-dev libavutil-dev libavcodec-dev libavformat-dev
            libprotoc-dev libprotobuf-dev protobuf-compiler
            qtbase5-dev libtinyxml2-dev
            libignition-cmake-dev
            libignition-math4-dev
            libignition-msgs-dev
            libignition-transport3-dev
          # Static checking before building
          - sh tools/code_check.sh
          # Ignition common
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common -b default
          - cd ign-common
          - mkdir build
          - cd build
          - cmake .. -DENABLE_TESTS_COMPILATION=false
          - make install
          - cd ../..
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make install
          # Tests currently fail, graphics issue?
          # - make test
