image: ubuntu:xenial

pipelines:
  default:
    - step:
        script:
          - apt update
          - apt install -y build-essential wget cmake qtbase5-dev libtinyxml2-dev mercurial
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common
          - cd ign-common
          - mkdir build
          - cd build
          - cmake ..
          - make install
          - cd ../..
          - mkdir build
          - cd build
          - cmake ..
          - make install
