image: ubuntu:bionic

pipelines:
  default:
    - step:
        script:
          # Install dependencies
          - apt update
          - apt install -y
            build-essential wget cmake cppcheck mercurial
            qtbase5-dev libtinyxml2-dev libprotoc-dev libprotobuf-dev
            qtdeclarative5-dev
            qtquickcontrols2-5-dev
            qml-module-qtquick2
            qml-module-qtquick-controls
            qml-module-qtquick-controls2
            qml-module-qtquick-layouts
          # Static checking before building
          #- sh tools/code_check.sh
          # Ignition tools
          - hg clone http://bitbucket.org/ignitionrobotics/ign-tools -b default
          - cd ign-tools
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition cmake
          - hg clone http://bitbucket.org/ignitionrobotics/ign-cmake -b default
          - cd ign-cmake
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition math
          - hg clone http://bitbucket.org/ignitionrobotics/ign-math -b default
          - cd ign-math
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition common
          - apt install -y
            uuid-dev
            libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev
            libfreeimage-dev libgts-dev libswscale-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-common -b default
          - cd ign-common
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition msgs
          - apt install -y
            protobuf-compiler
          - hg clone http://bitbucket.org/ignitionrobotics/ign-msgs -b default
          - cd ign-msgs
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition transport
          - apt install -y
            libzmq3-dev
            libsqlite3-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-transport -b default
          - cd ign-transport
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition rendering
          - apt install -y
            libogre-1.9-dev
          - hg clone http://bitbucket.org/ignitionrobotics/ign-rendering -b default
          - cd ign-rendering
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          - cd ../..
          # Ignition GUI
          - mkdir build
          - cd build
          - cmake ..
          - make -j4 install
          # Tests currently fail, graphics issue?
          # - make test
